end modal js structure with api data
QuickerMaths/filmoteka-grupa2 pull request #14
Opened 2023-05-23 09:21 UTC by cmdspeed

2023-05-23 11:30 UTC, QuickerMaths requested changes

2023-05-23 11:30 UTC, QuickerMaths commented on src/js/modal.js
> +const Modal = async data => {
async tutaj nie nic nie robi

2023-05-23 11:30 UTC, QuickerMaths commented on src/js/modal.js
> +  const id = event.target.id;
event.target.id nie zadziała, bo dodajesz eventListener na cała listę filmów, a nie na pojedyńczy filmy. 
Zamień na event.target.parentNode.id

2023-05-23 11:30 UTC, QuickerMaths commented on src/js/modal.js
> +export { Modal };
ten export chyba nie potrzebny

2023-05-23 11:30 UTC, QuickerMaths commented on src/js/modal.js
> +const fetchInfo = async id => {
brakuje try catch, żeby poradzić sobie z ewentualnymi errorami

2023-05-23 11:30 UTC, QuickerMaths commented on src/js/modal.js
> +  const array = await fetch(`https://api.themoviedb.org/3/movie/${id}?api_key=${API_KEY}`);
Zamiast fetch użyj axios (jest już zainstalowany w package.json)

2023-05-23 11:37 UTC, QuickerMaths requested changes

2023-05-23 11:37 UTC, QuickerMaths commented on src/js/modal.js
> +  closeBtn.removeEventListener('click', () => {
tu chyba powinien być addEventListener

2023-05-23 11:37 UTC, QuickerMaths commented on src/js/modal.js
> +  cardFilm.removeEventListener('click', event => {
wydaje mi się ze usuwanie Litenera jest nie potrzebne, wystarczy ze modal będzie miał przeźroczysty backdrop który będzie zakrywał cały ekran  i to uniemożliwi użytkownikowi interakcje ze stroną gdy modal jest otwarty

2023-05-24 08:55 UTC, cmdspeed commented on src/js/modal.js
> +const Modal = async data => {
faktycznie, po zmianie zapomniałem usunąć ;)

2023-05-24 08:56 UTC, cmdspeed commented on src/js/modal.js
> +  const id = event.target.id;
ciężko na ślepo sprawdzić, na 1 karcie pobierało dobre id, zmieniłem ;)

2023-05-24 08:57 UTC, cmdspeed commented on src/js/modal.js
> +export { Modal };
import jest index.js

2023-05-24 09:03 UTC, cmdspeed commented on src/js/modal.js
> +const fetchInfo = async id => {
poprawione ;)

2023-05-24 09:10 UTC, cmdspeed commented on src/js/modal.js
> +  const array = await fetch(`https://api.themoviedb.org/3/movie/${id}?api_key=${API_KEY}`);
podmienione ;)

2023-05-24 09:10 UTC, cmdspeed commented on src/js/modal.js
> +  closeBtn.removeEventListener('click', () => {
tutaj usuwany jest czyli dobrze remove ;)

2023-05-24 09:13 UTC, cmdspeed commented on src/js/modal.js
> +  cardFilm.removeEventListener('click', event => {
treść zadania "należy nie zapomnieć usunąć listeners!" ;)

2023-05-24 09:14 UTC, merged