wstępna wersja wyszukiwania
QuickerMaths/filmoteka-grupa2 pull request #16
Opened 2023-05-23 16:41 UTC by lukaszkocela

Funkcjonalność wyszukiwania
Funkcjonalność braku wyników
Renderowanie listy wyszukiwania
Wstepne stylowania

2023-05-23 18:45 UTC, QuickerMaths commented on src/js/search.js
> +  return response.json();
axios autmatycznie konwertuje format json do str, takze .json nie potrzebne

2023-05-23 18:46 UTC, QuickerMaths commented on src/js/search.js
> +const renderMoviesCollection = moviesCollection => {
tą funkcje robi Przemek

2023-05-23 18:47 UTC, QuickerMaths commented on src/js/search.js
> +const genres = [
myśle, ze tu zamiast hard codded value powinno być mimo wszystko zapytanie do serwera i później np. zapisanie wyniku w localStorage, zeby poprawić wydajność i nie powtarzać zapytania

2023-05-23 18:48 UTC, QuickerMaths commented on src/js/search.js
> +  fetch(`${API_URL}/search/movie?api_key=${API_KEY}&query=${query}`)
trzymajmy się pobierania danych za pomocą axios

2023-05-23 18:53 UTC, QuickerMaths commented on src/js/search.js
> +const getMoviesForSearch = async (query, page = 1) => {
ta funkcja to dosłownie to samo co searchMovies, tylko ze tu jest try catch zastosowane

2023-05-23 18:57 UTC, QuickerMaths commented on src/js/search.js
> +const getMovieByIDForSearch = async id => {
ta funkcja nie jest nigdzie uzywana

2023-05-23 18:58 UTC, QuickerMaths commented on src/js/search.js
> +const getGenresForSearch = async () => {
ta funkcja nie jest nigdzie uzywana

2023-05-23 18:58 UTC, QuickerMaths commented on src/js/search.js
> +const searchMovies = async (query, page) => {
ta funkcja nie jest nigdzie uzywana

2023-05-23 19:02 UTC, QuickerMaths commented on src/js/search.js
> +searchForm.addEventListener('submit', event => {
indntyczny listern dodany wyzej

2023-05-24 10:10 UTC, QuickerMaths requested changes

2023-05-24 10:10 UTC, QuickerMaths commented on src/js/search.js
> +searchForm.addEventListener('submit', event => {
indntyczny listern dodany wyzej

2023-05-24 10:10 UTC, QuickerMaths commented on src/js/search.js
>      .then(response => response.json())
axios automatycznie konwertuje format json, także ta linijka jest nie potrzebna

2023-05-24 10:15 UTC, lukaszkocela commented on src/js/search.js
>      .then(response => response.json())
tak, wiem, za mało kawy...

2023-05-24 10:21 UTC, merged